/**
 * Crypto Buildings Registry
 * 
 * Complete registry of all 99 crypto-themed buildings for Crypto City.
 * Buildings are organized by category:
 *   - DeFi (23): Lending, DEX, yield protocols
 *   - Exchange (7): CEX headquarters
 *   - Chain (13): L1/L2 blockchain buildings
 *   - CT (10): Crypto Twitter culture
 *   - Meme (20): Meme coin culture
 *   - Plasma (18): Plasma ecosystem
 *   - Stablecoin (3): Stablecoin issuers
 *   - Infrastructure (5): Oracles, bridges, data providers
 * 
 * Economy Balancing Formula:
 *   - Base Yield = Real APY * 0.5 (halved for game balance)
 *   - Risk = Historical exploit rate + (1 - audit_score)
 *   - Population Boost = log(TVL_in_billions) * 20
 *   - Happiness = Community sentiment score (1-10) * 3
 * 
 * Tier-Based Ranges:
 *   | Tier        | Yield Range | Risk Range   | Cost Range |
 *   |-------------|-------------|--------------|------------|
 *   | institution | 5-15%       | 0.001-0.005  | 15k-35k    |
 *   | whale       | 10-25%      | 0.005-0.02   | 8k-15k     |
 *   | degen       | 15-40%      | 0.02-0.1     | 3k-8k      |
 *   | retail      | 3-10%       | 0.001-0.01   | 1k-5k      |
 */

import { 
  CryptoBuildingDefinition, 
  CryptoCategory 
} from './types';

// =============================================================================
// DEFI BUILDINGS (23)
// =============================================================================
// Major DeFi protocols represented as city landmarks.

export const DEFI_BUILDINGS: Record<string, CryptoBuildingDefinition> = {
  'aave_lending_tower': {
    id: 'aave_lending_tower',
    name: 'Aave Lending Tower',
    category: 'defi',
    footprint: { width: 3, height: 3 },
    icon: '🏦',
    isProcedural: true,
    cost: 15000,
    crypto: {
      tier: 'institution',
      protocol: 'Aave',
      chain: 'ethereum',
      launchYear: 2020,
      tvlTier: 'massive',
      description: 'The iconic Aave Lending Tower dominates the DeFi district skyline.',
      effects: {
        yieldRate: 15,
        stakingBonus: 1.15,
        volatility: 0.1,
        rugRisk: 0.001,
        populationBoost: 50,
        happinessEffect: 10,
        zoneRadius: 8,
        chainSynergy: ['ethereum', 'arbitrum', 'optimism', 'polygon'],
        categorySynergy: ['defi'],
      },
    },
  },
  'uniswap_exchange': {
    id: 'uniswap_exchange',
    name: 'Uniswap Exchange',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🦄',
    isProcedural: true,
    cost: 10000,
    crypto: {
      tier: 'whale',
      protocol: 'Uniswap',
      chain: 'ethereum',
      launchYear: 2018,
      tvlTier: 'massive',
      description: 'The pink unicorn-topped Uniswap Exchange processes millions in trades daily.',
      effects: {
        yieldRate: 12,
        tradingFees: 20,
        volatility: 0.2,
        rugRisk: 0.002,
        populationBoost: 40,
        happinessEffect: 8,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'arbitrum', 'base', 'polygon'],
        categorySynergy: ['defi', 'exchange'],
      },
    },
  },
  'lido_staking_hub': {
    id: 'lido_staking_hub',
    name: 'Lido Staking Hub',
    category: 'defi',
    footprint: { width: 3, height: 2 },
    icon: '🌊',
    isProcedural: true,
    cost: 12000,
    crypto: {
      tier: 'institution',
      protocol: 'Lido',
      chain: 'ethereum',
      launchYear: 2020,
      tvlTier: 'massive',
      description: 'The serene Lido Staking Hub offers liquid staking for ETH.',
      effects: {
        yieldRate: 18,
        stakingBonus: 1.2,
        volatility: 0.05,
        rugRisk: 0.001,
        populationBoost: 35,
        happinessEffect: 12,
        zoneRadius: 7,
        chainSynergy: ['ethereum'],
        categorySynergy: ['defi', 'chain'],
      },
    },
  },
  'pendle_yield_factory': {
    id: 'pendle_yield_factory',
    name: 'Pendle Yield Factory',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '⚗️',
    isProcedural: true,
    cost: 8000,
    crypto: {
      tier: 'whale',
      protocol: 'Pendle',
      chain: 'ethereum',
      launchYear: 2021,
      tvlTier: 'high',
      description: 'The Pendle Yield Factory splits yield into principal and yield tokens.',
      effects: {
        yieldRate: 25,
        stakingBonus: 1.1,
        volatility: 0.25,
        rugRisk: 0.005,
        airdropChance: 0.02,
        populationBoost: 25,
        happinessEffect: 5,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'arbitrum'],
        categorySynergy: ['defi'],
      },
    },
  },
  'curve_finance_pool': {
    id: 'curve_finance_pool',
    name: 'Curve Finance Pool',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🌀',
    isProcedural: true,
    cost: 11000,
    crypto: {
      tier: 'institution',
      protocol: 'Curve',
      chain: 'ethereum',
      launchYear: 2020,
      tvlTier: 'massive',
      description: 'The curved Curve Finance building specializes in stablecoin swaps.',
      effects: {
        yieldRate: 10,
        stakingBonus: 1.08,
        volatility: 0.03,
        rugRisk: 0.001,
        populationBoost: 30,
        happinessEffect: 15,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'arbitrum', 'polygon'],
        categorySynergy: ['defi'],
      },
    },
  },
  'makerdao_vault': {
    id: 'makerdao_vault',
    name: 'MakerDAO Vault',
    category: 'defi',
    footprint: { width: 3, height: 3 },
    icon: '🏛️',
    isProcedural: true,
    cost: 14000,
    crypto: {
      tier: 'institution',
      protocol: 'MakerDAO',
      chain: 'ethereum',
      launchYear: 2017,
      tvlTier: 'massive',
      description: 'The MakerDAO Vault mints DAI stablecoin from collateralized assets.',
      effects: {
        yieldRate: 8,
        stakingBonus: 1.05,
        volatility: 0.02,
        rugRisk: 0.001,
        populationBoost: 45,
        happinessEffect: 20,
        zoneRadius: 7,
        chainSynergy: ['ethereum'],
        categorySynergy: ['defi'],
      },
    },
  },
  'compound_bank': {
    id: 'compound_bank',
    name: 'Compound Bank',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🏧',
    isProcedural: true,
    cost: 9000,
    crypto: {
      tier: 'whale',
      protocol: 'Compound',
      chain: 'ethereum',
      launchYear: 2018,
      tvlTier: 'high',
      description: 'Compound Bank pioneered algorithmic money markets.',
      effects: {
        yieldRate: 11,
        stakingBonus: 1.12,
        volatility: 0.08,
        rugRisk: 0.002,
        populationBoost: 30,
        happinessEffect: 10,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'base'],
        categorySynergy: ['defi'],
      },
    },
  },
  'eigenlayer_restaking': {
    id: 'eigenlayer_restaking',
    name: 'EigenLayer Restaking',
    category: 'defi',
    footprint: { width: 2, height: 3 },
    icon: '🔗',
    isProcedural: true,
    cost: 13000,
    crypto: {
      tier: 'institution',
      protocol: 'EigenLayer',
      chain: 'ethereum',
      launchYear: 2023,
      tvlTier: 'massive',
      description: 'EigenLayer enables restaking of ETH for additional yield.',
      effects: {
        yieldRate: 22,
        stakingBonus: 1.25,
        volatility: 0.15,
        rugRisk: 0.003,
        airdropChance: 0.05,
        populationBoost: 40,
        happinessEffect: 8,
        zoneRadius: 6,
        chainSynergy: ['ethereum'],
        categorySynergy: ['defi', 'chain'],
      },
    },
  },
  'balancer_vault': {
    id: 'balancer_vault',
    name: 'Balancer Vault',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '⚖️',
    isProcedural: true,
    cost: 7500,
    crypto: {
      tier: 'whale',
      protocol: 'Balancer',
      chain: 'ethereum',
      launchYear: 2020,
      tvlTier: 'high',
      description: 'Balancer Vault enables customizable liquidity pools.',
      effects: {
        yieldRate: 14,
        tradingFees: 15,
        volatility: 0.12,
        rugRisk: 0.003,
        populationBoost: 25,
        happinessEffect: 6,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'arbitrum', 'polygon'],
        categorySynergy: ['defi'],
      },
    },
  },
  'yearn_vault': {
    id: 'yearn_vault',
    name: 'Yearn Vault',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🏰',
    isProcedural: true,
    cost: 8500,
    crypto: {
      tier: 'whale',
      protocol: 'Yearn',
      chain: 'ethereum',
      launchYear: 2020,
      tvlTier: 'high',
      description: 'Yearn Vault automatically optimizes yield strategies.',
      effects: {
        yieldRate: 16,
        stakingBonus: 1.18,
        volatility: 0.1,
        rugRisk: 0.002,
        populationBoost: 28,
        happinessEffect: 7,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'arbitrum'],
        categorySynergy: ['defi'],
      },
    },
  },
  'convex_factory': {
    id: 'convex_factory',
    name: 'Convex Factory',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🏭',
    isProcedural: true,
    cost: 7000,
    crypto: {
      tier: 'whale',
      protocol: 'Convex',
      chain: 'ethereum',
      launchYear: 2021,
      tvlTier: 'high',
      description: 'Convex Factory boosts Curve LP rewards.',
      effects: {
        yieldRate: 13,
        stakingBonus: 1.15,
        volatility: 0.08,
        rugRisk: 0.002,
        populationBoost: 22,
        happinessEffect: 5,
        zoneRadius: 4,
        chainSynergy: ['ethereum'],
        categorySynergy: ['defi'],
      },
    },
  },
  'frax_mint': {
    id: 'frax_mint',
    name: 'Frax Mint',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '💱',
    isProcedural: true,
    cost: 8000,
    crypto: {
      tier: 'whale',
      protocol: 'Frax',
      chain: 'ethereum',
      launchYear: 2020,
      tvlTier: 'high',
      description: 'Frax Mint produces the algorithmic stablecoin FRAX.',
      effects: {
        yieldRate: 9,
        stakingBonus: 1.1,
        volatility: 0.04,
        rugRisk: 0.003,
        populationBoost: 24,
        happinessEffect: 8,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'arbitrum'],
        categorySynergy: ['defi'],
      },
    },
  },
  'eigenlayer_vault': {
    id: 'eigenlayer_vault',
    name: 'Eigenlayer Vault',
    category: 'defi',
    footprint: { width: 3, height: 3 },
    icon: '🔄',
    isProcedural: true,
    cost: 20000,
    crypto: {
      tier: 'institution',
      protocol: 'Eigenlayer',
      chain: 'ethereum',
      launchYear: 2023,
      tvlTier: 'massive',
      description: 'Eigenlayer Vault enables restaking for additional yield.',
      effects: {
        yieldRate: 20,
        stakingBonus: 1.35,
        volatility: 0.15,
        rugRisk: 0.008,
        airdropChance: 0.04,
        populationBoost: 60,
        happinessEffect: 12,
        zoneRadius: 8,
        chainSynergy: ['ethereum'],
        categorySynergy: ['defi', 'chain'],
      },
    },
  },
  'morpho_optimizer': {
    id: 'morpho_optimizer',
    name: 'Morpho Optimizer',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🦋',
    isProcedural: true,
    cost: 11000,
    crypto: {
      tier: 'whale',
      protocol: 'Morpho',
      chain: 'ethereum',
      launchYear: 2022,
      tvlTier: 'high',
      description: 'Morpho Optimizer improves lending rates with P2P matching.',
      effects: {
        yieldRate: 14,
        stakingBonus: 1.12,
        volatility: 0.08,
        rugRisk: 0.005,
        populationBoost: 35,
        happinessEffect: 8,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'base'],
        categorySynergy: ['defi'],
      },
    },
  },
  'maple_finance': {
    id: 'maple_finance',
    name: 'Maple Finance',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🍁',
    isProcedural: true,
    cost: 15000,
    crypto: {
      tier: 'institution',
      protocol: 'Maple',
      chain: 'ethereum',
      launchYear: 2021,
      tvlTier: 'high',
      description: 'Maple Finance provides undercollateralized institutional loans.',
      effects: {
        yieldRate: 12,
        stakingBonus: 1.08,
        volatility: 0.06,
        rugRisk: 0.01,
        populationBoost: 45,
        happinessEffect: 10,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'solana'],
        categorySynergy: ['defi'],
      },
    },
  },
  'spark_protocol': {
    id: 'spark_protocol',
    name: 'Spark Protocol',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '✨',
    isProcedural: true,
    cost: 10000,
    crypto: {
      tier: 'whale',
      protocol: 'Spark',
      chain: 'ethereum',
      launchYear: 2023,
      tvlTier: 'high',
      description: 'Spark Protocol brings lending to the MakerDAO ecosystem.',
      effects: {
        yieldRate: 10,
        stakingBonus: 1.1,
        volatility: 0.05,
        rugRisk: 0.004,
        populationBoost: 32,
        happinessEffect: 10,
        zoneRadius: 5,
        chainSynergy: ['ethereum'],
        categorySynergy: ['defi', 'stablecoin'],
      },
    },
  },
  'ondo_finance': {
    id: 'ondo_finance',
    name: 'Ondo Finance',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🏛️',
    isProcedural: true,
    cost: 16000,
    crypto: {
      tier: 'institution',
      protocol: 'Ondo',
      chain: 'ethereum',
      launchYear: 2022,
      tvlTier: 'high',
      description: 'Ondo Finance tokenizes real-world assets like US Treasuries.',
      effects: {
        yieldRate: 8,
        stakingBonus: 1.05,
        volatility: 0.02,
        rugRisk: 0.003,
        populationBoost: 50,
        happinessEffect: 15,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'polygon'],
        categorySynergy: ['defi', 'stablecoin'],
      },
    },
  },
  'sky_money': {
    id: 'sky_money',
    name: 'Sky.money',
    category: 'defi',
    footprint: { width: 3, height: 2 },
    icon: '☁️',
    isProcedural: true,
    cost: 14000,
    crypto: {
      tier: 'institution',
      protocol: 'Sky',
      chain: 'ethereum',
      launchYear: 2024,
      tvlTier: 'high',
      description: 'Sky.money is the evolution of MakerDAO with USDS stablecoin.',
      effects: {
        yieldRate: 9,
        stakingBonus: 1.08,
        volatility: 0.03,
        rugRisk: 0.002,
        populationBoost: 42,
        happinessEffect: 12,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'base'],
        categorySynergy: ['defi', 'stablecoin'],
      },
    },
  },
  // Solana DeFi Protocols
  'jupiter_terminal': {
    id: 'jupiter_terminal',
    name: 'Jupiter Terminal',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🪐',
    isProcedural: true,
    cost: 12000,
    crypto: {
      tier: 'whale',
      protocol: 'Jupiter',
      chain: 'solana',
      launchYear: 2021,
      tvlTier: 'high',
      description: 'Jupiter Terminal aggregates the best swap routes on Solana.',
      effects: {
        yieldRate: 15,
        tradingFees: 25,
        volatility: 0.18,
        rugRisk: 0.008,
        airdropChance: 0.03,
        populationBoost: 45,
        happinessEffect: 10,
        zoneRadius: 6,
        chainSynergy: ['solana'],
        categorySynergy: ['defi', 'exchange'],
      },
    },
  },
  'raydium_pool': {
    id: 'raydium_pool',
    name: 'Raydium Pool',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '💧',
    isProcedural: true,
    cost: 9000,
    crypto: {
      tier: 'degen',
      protocol: 'Raydium',
      chain: 'solana',
      launchYear: 2021,
      tvlTier: 'high',
      description: 'Raydium Pool provides AMM liquidity on Solana.',
      effects: {
        yieldRate: 18,
        tradingFees: 20,
        volatility: 0.25,
        rugRisk: 0.015,
        populationBoost: 35,
        happinessEffect: 6,
        zoneRadius: 5,
        chainSynergy: ['solana'],
        categorySynergy: ['defi'],
      },
    },
  },
  'orca_whirlpool': {
    id: 'orca_whirlpool',
    name: 'Orca Whirlpool',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🐋',
    isProcedural: true,
    cost: 10000,
    crypto: {
      tier: 'degen',
      protocol: 'Orca',
      chain: 'solana',
      launchYear: 2021,
      tvlTier: 'high',
      description: 'Orca Whirlpool offers concentrated liquidity on Solana.',
      effects: {
        yieldRate: 16,
        tradingFees: 18,
        volatility: 0.22,
        rugRisk: 0.012,
        populationBoost: 38,
        happinessEffect: 8,
        zoneRadius: 5,
        chainSynergy: ['solana'],
        categorySynergy: ['defi'],
      },
    },
  },
  'kamino_finance': {
    id: 'kamino_finance',
    name: 'Kamino Finance',
    category: 'defi',
    footprint: { width: 2, height: 2 },
    icon: '🎯',
    isProcedural: true,
    cost: 11000,
    crypto: {
      tier: 'whale',
      protocol: 'Kamino',
      chain: 'solana',
      launchYear: 2022,
      tvlTier: 'high',
      description: 'Kamino Finance auto-compounds concentrated liquidity positions.',
      effects: {
        yieldRate: 20,
        stakingBonus: 1.15,
        volatility: 0.2,
        rugRisk: 0.01,
        airdropChance: 0.02,
        populationBoost: 40,
        happinessEffect: 8,
        zoneRadius: 5,
        chainSynergy: ['solana'],
        categorySynergy: ['defi'],
      },
    },
  },
  'hyperliquid_vault': {
    id: 'hyperliquid_vault',
    name: 'Hyperliquid Vault',
    category: 'defi',
    footprint: { width: 3, height: 3 },
    icon: '💧',
    isProcedural: true,
    cost: 18000,
    crypto: {
      tier: 'institution',
      protocol: 'Hyperliquid',
      chain: 'hyperliquid',
      launchYear: 2023,
      tvlTier: 'massive',
      description: 'Hyperliquid Vault powers the fastest perps DEX on its own L1.',
      effects: {
        yieldRate: 22,
        tradingFees: 35,
        volatility: 0.18,
        rugRisk: 0.005,
        airdropChance: 0.08,
        populationBoost: 55,
        happinessEffect: 15,
        zoneRadius: 7,
        chainSynergy: ['hyperliquid', 'ethereum'],
        categorySynergy: ['defi', 'exchange'],
      },
    },
  },
};

// =============================================================================
// EXCHANGE BUILDINGS (7)
// =============================================================================
// Centralized exchange headquarters and trading facilities.

export const EXCHANGE_BUILDINGS: Record<string, CryptoBuildingDefinition> = {
  'binance_tower': {
    id: 'binance_tower',
    name: 'Binance Tower',
    category: 'exchange',
    footprint: { width: 4, height: 4 },
    icon: '🏢',
    isProcedural: true,
    cost: 25000,
    crypto: {
      tier: 'institution',
      protocol: 'Binance',
      chain: 'bnb',
      launchYear: 2017,
      tvlTier: 'massive',
      description: 'The massive Binance Tower is the largest crypto exchange HQ.',
      effects: {
        yieldRate: 20,
        tradingFees: 50,
        volatility: 0.15,
        rugRisk: 0.005,
        populationBoost: 100,
        happinessEffect: 15,
        zoneRadius: 10,
        chainSynergy: ['bnb', 'ethereum'],
        categorySynergy: ['exchange', 'defi'],
      },
    },
  },
  'coinbase_hq': {
    id: 'coinbase_hq',
    name: 'Coinbase HQ',
    category: 'exchange',
    footprint: { width: 3, height: 3 },
    icon: '🪙',
    isProcedural: true,
    cost: 20000,
    crypto: {
      tier: 'institution',
      protocol: 'Coinbase',
      chain: 'base',
      launchYear: 2012,
      tvlTier: 'massive',
      description: 'The Coinbase HQ brings institutional legitimacy to crypto.',
      effects: {
        yieldRate: 15,
        tradingFees: 40,
        volatility: 0.1,
        rugRisk: 0.002,
        populationBoost: 80,
        happinessEffect: 20,
        zoneRadius: 9,
        chainSynergy: ['base', 'ethereum'],
        categorySynergy: ['exchange'],
      },
    },
  },
  'kraken_exchange': {
    id: 'kraken_exchange',
    name: 'Kraken Exchange',
    category: 'exchange',
    footprint: { width: 2, height: 3 },
    icon: '🦑',
    isProcedural: true,
    cost: 15000,
    crypto: {
      tier: 'whale',
      protocol: 'Kraken',
      chain: 'ethereum',
      launchYear: 2011,
      tvlTier: 'high',
      description: 'The Kraken Exchange is a veteran trading platform.',
      effects: {
        yieldRate: 12,
        tradingFees: 30,
        volatility: 0.08,
        rugRisk: 0.002,
        populationBoost: 50,
        happinessEffect: 12,
        zoneRadius: 7,
        chainSynergy: ['ethereum', 'bitcoin'],
        categorySynergy: ['exchange'],
      },
    },
  },
  'okx_center': {
    id: 'okx_center',
    name: 'OKX Center',
    category: 'exchange',
    footprint: { width: 3, height: 2 },
    icon: '🅾️',
    isProcedural: true,
    cost: 14000,
    crypto: {
      tier: 'whale',
      protocol: 'OKX',
      chain: 'ethereum',
      launchYear: 2017,
      tvlTier: 'high',
      description: 'OKX Center serves global crypto traders.',
      effects: {
        yieldRate: 11,
        tradingFees: 28,
        volatility: 0.12,
        rugRisk: 0.004,
        populationBoost: 45,
        happinessEffect: 10,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'solana'],
        categorySynergy: ['exchange'],
      },
    },
  },
  'bybit_arena': {
    id: 'bybit_arena',
    name: 'Bybit Arena',
    category: 'exchange',
    footprint: { width: 2, height: 2 },
    icon: '🎯',
    isProcedural: true,
    cost: 12000,
    crypto: {
      tier: 'whale',
      protocol: 'Bybit',
      chain: 'ethereum',
      launchYear: 2018,
      tvlTier: 'high',
      description: 'Bybit Arena hosts derivatives trading competitions.',
      effects: {
        yieldRate: 14,
        tradingFees: 35,
        volatility: 0.2,
        rugRisk: 0.005,
        populationBoost: 40,
        happinessEffect: 8,
        zoneRadius: 5,
        chainSynergy: ['ethereum'],
        categorySynergy: ['exchange'],
      },
    },
  },
  'kucoin_plaza': {
    id: 'kucoin_plaza',
    name: 'KuCoin Plaza',
    category: 'exchange',
    footprint: { width: 2, height: 2 },
    icon: '🥝',
    isProcedural: true,
    cost: 10000,
    crypto: {
      tier: 'whale',
      protocol: 'KuCoin',
      chain: 'ethereum',
      launchYear: 2017,
      tvlTier: 'medium',
      description: 'KuCoin Plaza lists emerging altcoins.',
      effects: {
        yieldRate: 10,
        tradingFees: 25,
        volatility: 0.18,
        rugRisk: 0.008,
        airdropChance: 0.03,
        populationBoost: 35,
        happinessEffect: 6,
        zoneRadius: 5,
        chainSynergy: ['ethereum'],
        categorySynergy: ['exchange'],
      },
    },
  },
  'gemini_office': {
    id: 'gemini_office',
    name: 'Gemini Office',
    category: 'exchange',
    footprint: { width: 2, height: 2 },
    icon: '♊',
    isProcedural: true,
    cost: 11000,
    crypto: {
      tier: 'whale',
      protocol: 'Gemini',
      chain: 'ethereum',
      launchYear: 2014,
      tvlTier: 'medium',
      description: 'Gemini Office emphasizes regulatory compliance.',
      effects: {
        yieldRate: 8,
        tradingFees: 20,
        volatility: 0.05,
        rugRisk: 0.001,
        populationBoost: 30,
        happinessEffect: 15,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'bitcoin'],
        categorySynergy: ['exchange'],
      },
    },
  },
};

// =============================================================================
// CHAIN BUILDINGS (13)
// =============================================================================
// Blockchain-specific headquarters and landmarks.

export const CHAIN_BUILDINGS: Record<string, CryptoBuildingDefinition> = {
  'ethereum_beacon': {
    id: 'ethereum_beacon',
    name: 'Ethereum Beacon',
    category: 'chain',
    footprint: { width: 4, height: 4 },
    icon: '⟠',
    isProcedural: true,
    cost: 30000,
    crypto: {
      tier: 'institution',
      chain: 'ethereum',
      launchYear: 2015,
      tvlTier: 'massive',
      description: 'The Ethereum Beacon tower symbolizes the proof-of-stake transition.',
      effects: {
        yieldRate: 25,
        stakingBonus: 1.3,
        volatility: 0.1,
        rugRisk: 0.001,
        populationBoost: 120,
        happinessEffect: 25,
        zoneRadius: 12,
        chainSynergy: ['ethereum', 'arbitrum', 'optimism', 'base', 'polygon'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
  'solana_tower': {
    id: 'solana_tower',
    name: 'Solana Tower',
    category: 'chain',
    footprint: { width: 3, height: 3 },
    icon: '◎',
    isProcedural: true,
    cost: 22000,
    crypto: {
      tier: 'institution',
      chain: 'solana',
      launchYear: 2020,
      tvlTier: 'massive',
      description: 'The ultra-fast Solana Tower processes thousands of TPS.',
      effects: {
        yieldRate: 20,
        stakingBonus: 1.25,
        volatility: 0.25,
        rugRisk: 0.01,
        populationBoost: 80,
        happinessEffect: 18,
        zoneRadius: 10,
        chainSynergy: ['solana'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
  'bitcoin_vault': {
    id: 'bitcoin_vault',
    name: 'Bitcoin Vault',
    category: 'chain',
    footprint: { width: 3, height: 3 },
    icon: '₿',
    isProcedural: true,
    cost: 35000,
    crypto: {
      tier: 'institution',
      chain: 'bitcoin',
      launchYear: 2009,
      tvlTier: 'massive',
      description: 'The legendary Bitcoin Vault holds the original crypto treasure.',
      effects: {
        yieldRate: 5,
        stakingBonus: 1.0,
        volatility: 0.15,
        rugRisk: 0.0,
        populationBoost: 150,
        happinessEffect: 30,
        zoneRadius: 15,
        chainSynergy: ['bitcoin'],
        categorySynergy: ['chain'],
      },
    },
  },
  'arbitrum_bridge': {
    id: 'arbitrum_bridge',
    name: 'Arbitrum Bridge',
    category: 'chain',
    footprint: { width: 2, height: 3 },
    icon: '🌉',
    isProcedural: true,
    cost: 15000,
    crypto: {
      tier: 'whale',
      chain: 'arbitrum',
      launchYear: 2021,
      tvlTier: 'high',
      description: 'The Arbitrum Bridge connects L1 to fast L2 execution.',
      effects: {
        yieldRate: 18,
        stakingBonus: 1.15,
        volatility: 0.12,
        rugRisk: 0.003,
        airdropChance: 0.04,
        populationBoost: 55,
        happinessEffect: 12,
        zoneRadius: 7,
        chainSynergy: ['arbitrum', 'ethereum'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
  'optimism_hub': {
    id: 'optimism_hub',
    name: 'Optimism Hub',
    category: 'chain',
    footprint: { width: 2, height: 2 },
    icon: '🔴',
    isProcedural: true,
    cost: 14000,
    crypto: {
      tier: 'whale',
      chain: 'optimism',
      launchYear: 2021,
      tvlTier: 'high',
      description: 'The Optimism Hub spreads positive vibes and fast transactions.',
      effects: {
        yieldRate: 16,
        stakingBonus: 1.12,
        volatility: 0.1,
        rugRisk: 0.003,
        airdropChance: 0.03,
        populationBoost: 50,
        happinessEffect: 15,
        zoneRadius: 6,
        chainSynergy: ['optimism', 'ethereum'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
  'polygon_plaza': {
    id: 'polygon_plaza',
    name: 'Polygon Plaza',
    category: 'chain',
    footprint: { width: 2, height: 2 },
    icon: '💜',
    isProcedural: true,
    cost: 12000,
    crypto: {
      tier: 'whale',
      chain: 'polygon',
      launchYear: 2017,
      tvlTier: 'high',
      description: 'Polygon Plaza offers cheap and fast scaling solutions.',
      effects: {
        yieldRate: 14,
        stakingBonus: 1.1,
        volatility: 0.08,
        rugRisk: 0.004,
        populationBoost: 45,
        happinessEffect: 10,
        zoneRadius: 6,
        chainSynergy: ['polygon', 'ethereum'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
  'base_camp': {
    id: 'base_camp',
    name: 'Base Camp',
    category: 'chain',
    footprint: { width: 2, height: 2 },
    icon: '🔵',
    isProcedural: true,
    cost: 13000,
    crypto: {
      tier: 'whale',
      chain: 'base',
      launchYear: 2023,
      tvlTier: 'high',
      description: 'Base Camp is the launchpad for onchain activities.',
      effects: {
        yieldRate: 15,
        stakingBonus: 1.1,
        volatility: 0.12,
        rugRisk: 0.003,
        airdropChance: 0.05,
        populationBoost: 48,
        happinessEffect: 12,
        zoneRadius: 6,
        chainSynergy: ['base', 'ethereum'],
        categorySynergy: ['chain', 'exchange'],
      },
    },
  },
  'avalanche_summit': {
    id: 'avalanche_summit',
    name: 'Avalanche Summit',
    category: 'chain',
    footprint: { width: 2, height: 2 },
    icon: '🏔️',
    isProcedural: true,
    cost: 11000,
    crypto: {
      tier: 'whale',
      chain: 'avalanche',
      launchYear: 2020,
      tvlTier: 'medium',
      description: 'Avalanche Summit rises above with subnet technology.',
      effects: {
        yieldRate: 12,
        stakingBonus: 1.08,
        volatility: 0.15,
        rugRisk: 0.005,
        populationBoost: 40,
        happinessEffect: 8,
        zoneRadius: 5,
        chainSynergy: ['avalanche'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
  'zksync_tower': {
    id: 'zksync_tower',
    name: 'zkSync Era Tower',
    category: 'chain',
    footprint: { width: 2, height: 3 },
    icon: '🔐',
    isProcedural: true,
    cost: 14000,
    crypto: {
      tier: 'whale',
      chain: 'zksync',
      launchYear: 2023,
      tvlTier: 'high',
      description: 'zkSync Era Tower uses zero-knowledge proofs for scaling.',
      effects: {
        yieldRate: 16,
        stakingBonus: 1.12,
        volatility: 0.12,
        rugRisk: 0.005,
        airdropChance: 0.04,
        populationBoost: 45,
        happinessEffect: 10,
        zoneRadius: 6,
        chainSynergy: ['zksync', 'ethereum'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
  'scroll_campus': {
    id: 'scroll_campus',
    name: 'Scroll Campus',
    category: 'chain',
    footprint: { width: 2, height: 2 },
    icon: '📜',
    isProcedural: true,
    cost: 12000,
    crypto: {
      tier: 'whale',
      chain: 'scroll',
      launchYear: 2023,
      tvlTier: 'medium',
      description: 'Scroll Campus advances EVM-equivalent zkRollup technology.',
      effects: {
        yieldRate: 14,
        stakingBonus: 1.08,
        volatility: 0.1,
        rugRisk: 0.006,
        airdropChance: 0.03,
        populationBoost: 38,
        happinessEffect: 8,
        zoneRadius: 5,
        chainSynergy: ['scroll', 'ethereum'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
  'linea_station': {
    id: 'linea_station',
    name: 'Linea Station',
    category: 'chain',
    footprint: { width: 2, height: 2 },
    icon: '🚉',
    isProcedural: true,
    cost: 11000,
    crypto: {
      tier: 'whale',
      chain: 'linea',
      launchYear: 2023,
      tvlTier: 'medium',
      description: 'Linea Station connects the ConsenSys ecosystem.',
      effects: {
        yieldRate: 12,
        stakingBonus: 1.06,
        volatility: 0.08,
        rugRisk: 0.004,
        airdropChance: 0.02,
        populationBoost: 35,
        happinessEffect: 10,
        zoneRadius: 5,
        chainSynergy: ['linea', 'ethereum'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
  'blast_arena': {
    id: 'blast_arena',
    name: 'Blast Arena',
    category: 'chain',
    footprint: { width: 2, height: 2 },
    icon: '💥',
    isProcedural: true,
    cost: 10000,
    crypto: {
      tier: 'degen',
      chain: 'blast',
      launchYear: 2024,
      tvlTier: 'high',
      description: 'Blast Arena offers native yield on ETH and stablecoins.',
      effects: {
        yieldRate: 20,
        stakingBonus: 1.15,
        volatility: 0.2,
        rugRisk: 0.015,
        airdropChance: 0.05,
        populationBoost: 42,
        happinessEffect: 8,
        zoneRadius: 5,
        chainSynergy: ['blast', 'ethereum'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
  'mantle_hub': {
    id: 'mantle_hub',
    name: 'Mantle Hub',
    category: 'chain',
    footprint: { width: 2, height: 2 },
    icon: '🧥',
    isProcedural: true,
    cost: 12000,
    crypto: {
      tier: 'whale',
      chain: 'mantle',
      launchYear: 2023,
      tvlTier: 'high',
      description: 'Mantle Hub is backed by BitDAO treasury.',
      effects: {
        yieldRate: 14,
        stakingBonus: 1.1,
        volatility: 0.1,
        rugRisk: 0.005,
        populationBoost: 40,
        happinessEffect: 10,
        zoneRadius: 5,
        chainSynergy: ['mantle', 'ethereum'],
        categorySynergy: ['chain', 'defi'],
      },
    },
  },
};

// =============================================================================
// CT (CRYPTO TWITTER) CULTURE BUILDINGS (10)
// =============================================================================
// Buildings representing crypto Twitter culture and community.

export const CT_BUILDINGS: Record<string, CryptoBuildingDefinition> = {
  'ct_studio': {
    id: 'ct_studio',
    name: 'CT Influencer Studio',
    category: 'ct',
    footprint: { width: 2, height: 2 },
    icon: '🎙️',
    isProcedural: true,
    cost: 6000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'The CT Studio broadcasts alpha to thousands of followers.',
      effects: {
        yieldRate: 8,
        volatility: 0.3,
        rugRisk: 0.02,
        populationBoost: 30,
        happinessEffect: 5,
        zoneRadius: 4,
        chainSynergy: ['ethereum', 'solana'],
        categorySynergy: ['ct', 'meme'],
      },
    },
  },
  'vc_office': {
    id: 'vc_office',
    name: 'VC Office',
    category: 'ct',
    footprint: { width: 2, height: 2 },
    icon: '💼',
    isProcedural: true,
    cost: 15000,
    crypto: {
      tier: 'institution',
      chain: 'ethereum',
      description: 'The VC Office funds the next generation of protocols.',
      effects: {
        yieldRate: 5,
        volatility: 0.1,
        rugRisk: 0.01,
        airdropChance: 0.1,
        populationBoost: 40,
        happinessEffect: -5,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'solana'],
        categorySynergy: ['ct', 'defi'],
      },
    },
  },
  'alpha_call_center': {
    id: 'alpha_call_center',
    name: 'Alpha Call Center',
    category: 'ct',
    footprint: { width: 1, height: 2 },
    icon: '📞',
    isProcedural: true,
    cost: 5000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'The Alpha Call Center shares insider tips 24/7.',
      effects: {
        yieldRate: 12,
        volatility: 0.4,
        rugRisk: 0.05,
        populationBoost: 20,
        happinessEffect: 3,
        zoneRadius: 3,
        chainSynergy: ['ethereum', 'solana', 'base'],
        categorySynergy: ['ct'],
      },
    },
  },
  'podcast_tower': {
    id: 'podcast_tower',
    name: 'Podcast Tower',
    category: 'ct',
    footprint: { width: 2, height: 2 },
    icon: '🎧',
    isProcedural: true,
    cost: 7000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'The Podcast Tower hosts crypto thought leaders.',
      effects: {
        yieldRate: 6,
        volatility: 0.15,
        rugRisk: 0.01,
        populationBoost: 25,
        happinessEffect: 8,
        zoneRadius: 4,
        chainSynergy: ['ethereum'],
        categorySynergy: ['ct'],
      },
    },
  },
  'nft_gallery': {
    id: 'nft_gallery',
    name: 'NFT Gallery',
    category: 'ct',
    footprint: { width: 2, height: 2 },
    icon: '🖼️',
    isProcedural: true,
    cost: 8000,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'The NFT Gallery displays digital art collections.',
      effects: {
        yieldRate: 4,
        volatility: 0.5,
        rugRisk: 0.03,
        populationBoost: 35,
        happinessEffect: 15,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'solana'],
        categorySynergy: ['ct', 'meme'],
      },
    },
  },
  'dao_hq': {
    id: 'dao_hq',
    name: 'DAO HQ',
    category: 'ct',
    footprint: { width: 2, height: 2 },
    icon: '🏛️',
    isProcedural: true,
    cost: 10000,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'The DAO HQ coordinates decentralized governance.',
      effects: {
        yieldRate: 7,
        stakingBonus: 1.1,
        volatility: 0.2,
        rugRisk: 0.02,
        populationBoost: 30,
        happinessEffect: 10,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'arbitrum'],
        categorySynergy: ['ct', 'defi'],
      },
    },
  },
  'anon_bunker': {
    id: 'anon_bunker',
    name: 'Anon Bunker',
    category: 'ct',
    footprint: { width: 1, height: 1 },
    icon: '🕵️',
    isProcedural: true,
    cost: 4000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'The Anon Bunker protects pseudonymous identities.',
      effects: {
        yieldRate: 10,
        volatility: 0.35,
        rugRisk: 0.04,
        populationBoost: 15,
        happinessEffect: 2,
        zoneRadius: 2,
        chainSynergy: ['ethereum'],
        categorySynergy: ['ct'],
      },
    },
  },
  'degen_lounge': {
    id: 'degen_lounge',
    name: 'Degen Lounge',
    category: 'ct',
    footprint: { width: 2, height: 2 },
    icon: '🎰',
    isProcedural: true,
    cost: 5500,
    crypto: {
      tier: 'degen',
      chain: 'solana',
      description: 'The Degen Lounge is where apes gather to trade.',
      effects: {
        yieldRate: 20,
        volatility: 0.6,
        rugRisk: 0.08,
        populationBoost: 25,
        happinessEffect: 10,
        zoneRadius: 4,
        chainSynergy: ['solana', 'base'],
        categorySynergy: ['ct', 'meme'],
      },
    },
  },
  'whale_watching_tower': {
    id: 'whale_watching_tower',
    name: 'Whale Watching Tower',
    category: 'ct',
    footprint: { width: 1, height: 2 },
    icon: '🐋',
    isProcedural: true,
    cost: 6500,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'The Whale Watching Tower tracks large wallet movements.',
      effects: {
        yieldRate: 8,
        volatility: 0.2,
        rugRisk: 0.02,
        populationBoost: 20,
        happinessEffect: 5,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'bitcoin'],
        categorySynergy: ['ct', 'exchange'],
      },
    },
  },
  'fud_factory': {
    id: 'fud_factory',
    name: 'FUD Factory',
    category: 'ct',
    footprint: { width: 1, height: 1 },
    icon: '😱',
    isProcedural: true,
    cost: 3000,
    crypto: {
      tier: 'retail',
      chain: 'ethereum',
      description: 'The FUD Factory spreads fear, uncertainty, and doubt.',
      effects: {
        yieldRate: -5,
        volatility: 0.4,
        rugRisk: 0.01,
        populationBoost: 10,
        happinessEffect: -10,
        zoneRadius: 3,
        chainSynergy: ['ethereum'],
        categorySynergy: ['ct'],
      },
    },
  },
};

// =============================================================================
// MEME BUILDINGS (20)
// =============================================================================
// Buildings celebrating meme coin culture.

export const MEME_BUILDINGS: Record<string, CryptoBuildingDefinition> = {
  'pepe_statue': {
    id: 'pepe_statue',
    name: 'Pepe Statue',
    category: 'meme',
    footprint: { width: 1, height: 1 },
    icon: '🐸',
    isProcedural: true,
    cost: 2000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'The iconic Pepe Statue brings good luck to degens.',
      effects: {
        yieldRate: 5,
        volatility: 0.5,
        rugRisk: 0.05,
        populationBoost: 15,
        happinessEffect: 20,
        zoneRadius: 3,
        chainSynergy: ['ethereum'],
        categorySynergy: ['meme'],
      },
    },
  },
  'doge_fountain': {
    id: 'doge_fountain',
    name: 'Doge Fountain',
    category: 'meme',
    footprint: { width: 2, height: 2 },
    icon: '🐕',
    isProcedural: true,
    cost: 3500,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'The Doge Fountain celebrates the OG meme coin.',
      effects: {
        yieldRate: 8,
        volatility: 0.45,
        rugRisk: 0.03,
        populationBoost: 25,
        happinessEffect: 25,
        zoneRadius: 4,
        chainSynergy: ['ethereum'],
        categorySynergy: ['meme'],
      },
    },
  },
  'shiba_shrine': {
    id: 'shiba_shrine',
    name: 'Shiba Shrine',
    category: 'meme',
    footprint: { width: 2, height: 2 },
    icon: '🐕‍🦺',
    isProcedural: true,
    cost: 3000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'The Shiba Shrine honors the SHIB army.',
      effects: {
        yieldRate: 7,
        volatility: 0.5,
        rugRisk: 0.04,
        populationBoost: 22,
        happinessEffect: 22,
        zoneRadius: 4,
        chainSynergy: ['ethereum'],
        categorySynergy: ['meme'],
      },
    },
  },
  'wojak_memorial': {
    id: 'wojak_memorial',
    name: 'Wojak Memorial',
    category: 'meme',
    footprint: { width: 1, height: 1 },
    icon: '😭',
    isProcedural: true,
    cost: 1500,
    crypto: {
      tier: 'retail',
      chain: 'ethereum',
      description: 'The Wojak Memorial remembers all the losses.',
      effects: {
        yieldRate: 2,
        volatility: 0.3,
        rugRisk: 0.02,
        populationBoost: 10,
        happinessEffect: -5,
        zoneRadius: 2,
        chainSynergy: ['ethereum'],
        categorySynergy: ['meme', 'ct'],
      },
    },
  },
  'ape_enclosure': {
    id: 'ape_enclosure',
    name: 'Ape Enclosure',
    category: 'meme',
    footprint: { width: 2, height: 2 },
    icon: '🦍',
    isProcedural: true,
    cost: 4000,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'The Ape Enclosure houses BAYC and friends.',
      effects: {
        yieldRate: 6,
        volatility: 0.4,
        rugRisk: 0.03,
        populationBoost: 30,
        happinessEffect: 18,
        zoneRadius: 4,
        chainSynergy: ['ethereum'],
        categorySynergy: ['meme', 'ct'],
      },
    },
  },
  'moon_monument': {
    id: 'moon_monument',
    name: 'Moon Monument',
    category: 'meme',
    footprint: { width: 2, height: 3 },
    icon: '🌙',
    isProcedural: true,
    cost: 5000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'The Moon Monument points to where we\'re all heading.',
      effects: {
        yieldRate: 10,
        volatility: 0.5,
        rugRisk: 0.04,
        populationBoost: 35,
        happinessEffect: 30,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'solana'],
        categorySynergy: ['meme'],
      },
    },
  },
  'lambo_dealership': {
    id: 'lambo_dealership',
    name: 'Lambo Dealership',
    category: 'meme',
    footprint: { width: 3, height: 2 },
    icon: '🏎️',
    isProcedural: true,
    cost: 8000,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'The Lambo Dealership fulfills every degen\'s dream.',
      effects: {
        yieldRate: 4,
        volatility: 0.3,
        rugRisk: 0.02,
        populationBoost: 40,
        happinessEffect: 35,
        zoneRadius: 5,
        chainSynergy: ['ethereum'],
        categorySynergy: ['meme', 'ct'],
      },
    },
  },
  'diamond_hands_plaza': {
    id: 'diamond_hands_plaza',
    name: 'Diamond Hands Plaza',
    category: 'meme',
    footprint: { width: 2, height: 2 },
    icon: '💎',
    isProcedural: true,
    cost: 4500,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'Diamond Hands Plaza honors those who never sell.',
      effects: {
        yieldRate: 6,
        stakingBonus: 1.2,
        volatility: 0.2,
        rugRisk: 0.01,
        populationBoost: 28,
        happinessEffect: 20,
        zoneRadius: 4,
        chainSynergy: ['ethereum', 'bitcoin'],
        categorySynergy: ['meme'],
      },
    },
  },
  'paper_hands_recycling': {
    id: 'paper_hands_recycling',
    name: 'Paper Hands Recycling',
    category: 'meme',
    footprint: { width: 1, height: 1 },
    icon: '📄',
    isProcedural: true,
    cost: 1000,
    crypto: {
      tier: 'retail',
      chain: 'ethereum',
      description: 'Paper Hands Recycling processes panic sells.',
      effects: {
        yieldRate: -2,
        volatility: 0.4,
        rugRisk: 0.02,
        populationBoost: 5,
        happinessEffect: -8,
        zoneRadius: 2,
        chainSynergy: ['ethereum'],
        categorySynergy: ['meme'],
      },
    },
  },
  'fomo_tower': {
    id: 'fomo_tower',
    name: 'FOMO Tower',
    category: 'meme',
    footprint: { width: 1, height: 2 },
    icon: '🏃',
    isProcedural: true,
    cost: 3500,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'FOMO Tower broadcasts urgency signals 24/7.',
      effects: {
        yieldRate: 15,
        volatility: 0.6,
        rugRisk: 0.06,
        populationBoost: 20,
        happinessEffect: 5,
        zoneRadius: 4,
        chainSynergy: ['ethereum', 'solana'],
        categorySynergy: ['meme', 'ct'],
      },
    },
  },
  'hodl_bunker': {
    id: 'hodl_bunker',
    name: 'HODL Bunker',
    category: 'meme',
    footprint: { width: 2, height: 2 },
    icon: '🏠',
    isProcedural: true,
    cost: 5000,
    crypto: {
      tier: 'whale',
      chain: 'bitcoin',
      description: 'The HODL Bunker protects long-term holdings.',
      effects: {
        yieldRate: 3,
        stakingBonus: 1.3,
        volatility: 0.1,
        rugRisk: 0.0,
        populationBoost: 25,
        happinessEffect: 15,
        zoneRadius: 4,
        chainSynergy: ['bitcoin', 'ethereum'],
        categorySynergy: ['meme'],
      },
    },
  },
  'wagmi_cafe': {
    id: 'wagmi_cafe',
    name: 'WAGMI Café',
    category: 'meme',
    footprint: { width: 1, height: 1 },
    icon: '☕',
    isProcedural: true,
    cost: 2000,
    crypto: {
      tier: 'retail',
      chain: 'ethereum',
      description: 'WAGMI Café serves hopium to all visitors.',
      effects: {
        yieldRate: 4,
        volatility: 0.2,
        rugRisk: 0.01,
        populationBoost: 15,
        happinessEffect: 25,
        zoneRadius: 3,
        chainSynergy: ['ethereum'],
        categorySynergy: ['meme', 'ct'],
      },
    },
  },
  'ngmi_alley': {
    id: 'ngmi_alley',
    name: 'NGMI Alley',
    category: 'meme',
    footprint: { width: 1, height: 1 },
    icon: '🚫',
    isProcedural: true,
    cost: 500,
    crypto: {
      tier: 'retail',
      chain: 'ethereum',
      description: 'NGMI Alley is where bad trades end up.',
      effects: {
        yieldRate: -3,
        volatility: 0.5,
        rugRisk: 0.1,
        populationBoost: 5,
        happinessEffect: -15,
        zoneRadius: 2,
        chainSynergy: ['ethereum'],
        categorySynergy: ['meme'],
      },
    },
  },
  'gm_gn_tower': {
    id: 'gm_gn_tower',
    name: 'GM/GN Tower',
    category: 'meme',
    footprint: { width: 1, height: 2 },
    icon: '🌅',
    isProcedural: true,
    cost: 2500,
    crypto: {
      tier: 'retail',
      chain: 'ethereum',
      description: 'The GM/GN Tower greets the crypto community.',
      effects: {
        yieldRate: 5,
        volatility: 0.1,
        rugRisk: 0.01,
        populationBoost: 18,
        happinessEffect: 30,
        zoneRadius: 3,
        chainSynergy: ['ethereum', 'solana'],
        categorySynergy: ['meme', 'ct'],
      },
    },
  },
  'wif_temple': {
    id: 'wif_temple',
    name: 'WIF Temple',
    category: 'meme',
    footprint: { width: 2, height: 2 },
    icon: '🐕',
    isProcedural: true,
    cost: 4000,
    crypto: {
      tier: 'degen',
      chain: 'solana',
      description: 'The WIF Temple celebrates the legendary dogwifhat.',
      effects: {
        yieldRate: 12,
        volatility: 0.55,
        rugRisk: 0.04,
        populationBoost: 28,
        happinessEffect: 22,
        zoneRadius: 4,
        chainSynergy: ['solana'],
        categorySynergy: ['meme'],
      },
    },
  },
  'bonk_arena': {
    id: 'bonk_arena',
    name: 'BONK Arena',
    category: 'meme',
    footprint: { width: 2, height: 2 },
    icon: '🦴',
    isProcedural: true,
    cost: 3500,
    crypto: {
      tier: 'degen',
      chain: 'solana',
      description: 'The BONK Arena where Shiba Inu memes come to play.',
      effects: {
        yieldRate: 10,
        volatility: 0.5,
        rugRisk: 0.04,
        populationBoost: 25,
        happinessEffect: 20,
        zoneRadius: 4,
        chainSynergy: ['solana'],
        categorySynergy: ['meme'],
      },
    },
  },
  'popcat_pavilion': {
    id: 'popcat_pavilion',
    name: 'POPCAT Pavilion',
    category: 'meme',
    footprint: { width: 2, height: 2 },
    icon: '🐱',
    isProcedural: true,
    cost: 3800,
    crypto: {
      tier: 'degen',
      chain: 'solana',
      description: 'The POPCAT Pavilion echoes with endless clicking sounds.',
      effects: {
        yieldRate: 11,
        volatility: 0.52,
        rugRisk: 0.045,
        populationBoost: 26,
        happinessEffect: 24,
        zoneRadius: 4,
        chainSynergy: ['solana'],
        categorySynergy: ['meme'],
      },
    },
  },
  'brett_base': {
    id: 'brett_base',
    name: 'Brett Base',
    category: 'meme',
    footprint: { width: 2, height: 2 },
    icon: '🔵',
    isProcedural: true,
    cost: 4200,
    crypto: {
      tier: 'degen',
      chain: 'base',
      description: 'Brett Base is the home of Base chain\'s favorite frog.',
      effects: {
        yieldRate: 13,
        volatility: 0.48,
        rugRisk: 0.035,
        populationBoost: 30,
        happinessEffect: 18,
        zoneRadius: 4,
        chainSynergy: ['base'],
        categorySynergy: ['meme'],
      },
    },
  },
  'floki_fortress': {
    id: 'floki_fortress',
    name: 'Floki Fortress',
    category: 'meme',
    footprint: { width: 2, height: 3 },
    icon: '⚔️',
    isProcedural: true,
    cost: 5500,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'Floki Fortress stands as a Viking tribute to meme culture.',
      effects: {
        yieldRate: 9,
        volatility: 0.42,
        rugRisk: 0.03,
        populationBoost: 35,
        happinessEffect: 20,
        zoneRadius: 5,
        chainSynergy: ['ethereum', 'bnb'],
        categorySynergy: ['meme'],
      },
    },
  },
  'mog_mansion': {
    id: 'mog_mansion',
    name: 'MOG Mansion',
    category: 'meme',
    footprint: { width: 2, height: 2 },
    icon: '😎',
    isProcedural: true,
    cost: 4500,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'MOG Mansion is where the cool cats hang out.',
      effects: {
        yieldRate: 14,
        volatility: 0.55,
        rugRisk: 0.05,
        populationBoost: 28,
        happinessEffect: 25,
        zoneRadius: 4,
        chainSynergy: ['ethereum'],
        categorySynergy: ['meme', 'ct'],
      },
    },
  },
};

// =============================================================================
// PLASMA BUILDINGS (18)
// =============================================================================
// Custom themed buildings with Plasma branding.

export const PLASMA_BUILDINGS: Record<string, CryptoBuildingDefinition> = {
  'plasma_hq': {
    id: 'plasma_hq',
    name: 'Plasma HQ',
    category: 'plasma',
    footprint: { width: 4, height: 4 },
    icon: '🏢',
    isProcedural: true,
    cost: 50000,
    crypto: {
      tier: 'institution',
      chain: 'ethereum',
      description: 'The central Plasma headquarters.',
      effects: {
        yieldRate: 30,
        stakingBonus: 1.5,
        volatility: 0.05,
        rugRisk: 0.0,
        populationBoost: 200,
        happinessEffect: 40,
        zoneRadius: 15,
        chainSynergy: ['ethereum', 'arbitrum', 'optimism', 'base', 'polygon'],
        categorySynergy: ['plasma', 'defi', 'chain'],
      },
    },
  },
  'plasma_node': {
    id: 'plasma_node',
    name: 'Plasma Node',
    category: 'plasma',
    footprint: { width: 1, height: 1 },
    icon: '⚡',
    isProcedural: true,
    cost: 5000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'A Plasma network node.',
      effects: {
        yieldRate: 10,
        stakingBonus: 1.1,
        volatility: 0.1,
        rugRisk: 0.001,
        populationBoost: 15,
        happinessEffect: 5,
        zoneRadius: 3,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_bridge': {
    id: 'plasma_bridge',
    name: 'Plasma Bridge',
    category: 'plasma',
    footprint: { width: 2, height: 3 },
    icon: '🌉',
    isProcedural: true,
    cost: 12000,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'The Plasma cross-chain bridge.',
      effects: {
        yieldRate: 15,
        tradingFees: 20,
        volatility: 0.08,
        rugRisk: 0.002,
        populationBoost: 40,
        happinessEffect: 10,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'arbitrum', 'optimism'],
        categorySynergy: ['plasma', 'chain'],
      },
    },
  },
  'plasma_vault': {
    id: 'plasma_vault',
    name: 'Plasma Vault',
    category: 'plasma',
    footprint: { width: 2, height: 2 },
    icon: '🔐',
    isProcedural: true,
    cost: 15000,
    crypto: {
      tier: 'institution',
      chain: 'ethereum',
      description: 'Secure Plasma token storage.',
      effects: {
        yieldRate: 8,
        stakingBonus: 1.25,
        volatility: 0.03,
        rugRisk: 0.0,
        populationBoost: 30,
        happinessEffect: 15,
        zoneRadius: 5,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma', 'defi'],
      },
    },
  },
  'plasma_lab': {
    id: 'plasma_lab',
    name: 'Plasma Lab',
    category: 'plasma',
    footprint: { width: 2, height: 2 },
    icon: '🔬',
    isProcedural: true,
    cost: 10000,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'Plasma research and development.',
      effects: {
        yieldRate: 12,
        airdropChance: 0.05,
        volatility: 0.15,
        rugRisk: 0.002,
        populationBoost: 35,
        happinessEffect: 12,
        zoneRadius: 5,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_arena': {
    id: 'plasma_arena',
    name: 'Plasma Arena',
    category: 'plasma',
    footprint: { width: 3, height: 3 },
    icon: '🏟️',
    isProcedural: true,
    cost: 20000,
    crypto: {
      tier: 'institution',
      chain: 'ethereum',
      description: 'The Plasma community arena.',
      effects: {
        yieldRate: 5,
        volatility: 0.1,
        rugRisk: 0.001,
        populationBoost: 80,
        happinessEffect: 40,
        zoneRadius: 8,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma', 'ct'],
      },
    },
  },
  'plasma_tower': {
    id: 'plasma_tower',
    name: 'Plasma Tower',
    category: 'plasma',
    footprint: { width: 2, height: 3 },
    icon: '🗼',
    isProcedural: true,
    cost: 18000,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'A Plasma signal tower.',
      effects: {
        yieldRate: 14,
        volatility: 0.08,
        rugRisk: 0.001,
        populationBoost: 50,
        happinessEffect: 15,
        zoneRadius: 7,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_garden': {
    id: 'plasma_garden',
    name: 'Plasma Garden',
    category: 'plasma',
    footprint: { width: 2, height: 2 },
    icon: '🌳',
    isProcedural: true,
    cost: 6000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'A peaceful Plasma garden.',
      effects: {
        yieldRate: 6,
        volatility: 0.05,
        rugRisk: 0.001,
        populationBoost: 25,
        happinessEffect: 35,
        zoneRadius: 4,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_fountain': {
    id: 'plasma_fountain',
    name: 'Plasma Fountain',
    category: 'plasma',
    footprint: { width: 1, height: 1 },
    icon: '⛲',
    isProcedural: true,
    cost: 4000,
    crypto: {
      tier: 'retail',
      chain: 'ethereum',
      description: 'A decorative Plasma fountain.',
      effects: {
        yieldRate: 3,
        volatility: 0.03,
        rugRisk: 0.0,
        populationBoost: 15,
        happinessEffect: 25,
        zoneRadius: 3,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_monument': {
    id: 'plasma_monument',
    name: 'Plasma Monument',
    category: 'plasma',
    footprint: { width: 2, height: 2 },
    icon: '🗿',
    isProcedural: true,
    cost: 8000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'A Plasma historical monument.',
      effects: {
        yieldRate: 4,
        volatility: 0.05,
        rugRisk: 0.0,
        populationBoost: 30,
        happinessEffect: 30,
        zoneRadius: 4,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_gateway': {
    id: 'plasma_gateway',
    name: 'Plasma Gateway',
    category: 'plasma',
    footprint: { width: 2, height: 1 },
    icon: '🚪',
    isProcedural: true,
    cost: 7000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'The Plasma city entrance.',
      effects: {
        yieldRate: 5,
        volatility: 0.06,
        rugRisk: 0.001,
        populationBoost: 20,
        happinessEffect: 20,
        zoneRadius: 4,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_observatory': {
    id: 'plasma_observatory',
    name: 'Plasma Observatory',
    category: 'plasma',
    footprint: { width: 2, height: 2 },
    icon: '🔭',
    isProcedural: true,
    cost: 9000,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'The Plasma research observatory.',
      effects: {
        yieldRate: 8,
        airdropChance: 0.03,
        volatility: 0.1,
        rugRisk: 0.002,
        populationBoost: 28,
        happinessEffect: 18,
        zoneRadius: 5,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_reactor': {
    id: 'plasma_reactor',
    name: 'Plasma Reactor',
    category: 'plasma',
    footprint: { width: 3, height: 3 },
    icon: '⚛️',
    isProcedural: true,
    cost: 25000,
    crypto: {
      tier: 'institution',
      chain: 'ethereum',
      description: 'The Plasma energy reactor.',
      effects: {
        yieldRate: 25,
        stakingBonus: 1.3,
        volatility: 0.12,
        rugRisk: 0.003,
        populationBoost: 60,
        happinessEffect: 15,
        zoneRadius: 8,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_academy': {
    id: 'plasma_academy',
    name: 'Plasma Academy',
    category: 'plasma',
    footprint: { width: 3, height: 2 },
    icon: '🎓',
    isProcedural: true,
    cost: 12000,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'The Plasma education center.',
      effects: {
        yieldRate: 7,
        volatility: 0.05,
        rugRisk: 0.001,
        populationBoost: 45,
        happinessEffect: 25,
        zoneRadius: 6,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma', 'ct'],
      },
    },
  },
  'plasma_museum': {
    id: 'plasma_museum',
    name: 'Plasma Museum',
    category: 'plasma',
    footprint: { width: 2, height: 2 },
    icon: '🏛️',
    isProcedural: true,
    cost: 10000,
    crypto: {
      tier: 'whale',
      chain: 'ethereum',
      description: 'The Plasma history museum.',
      effects: {
        yieldRate: 4,
        volatility: 0.04,
        rugRisk: 0.0,
        populationBoost: 35,
        happinessEffect: 35,
        zoneRadius: 5,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_stadium': {
    id: 'plasma_stadium',
    name: 'Plasma Stadium',
    category: 'plasma',
    footprint: { width: 4, height: 3 },
    icon: '🏟️',
    isProcedural: true,
    cost: 30000,
    crypto: {
      tier: 'institution',
      chain: 'ethereum',
      description: 'The grand Plasma stadium.',
      effects: {
        yieldRate: 8,
        volatility: 0.08,
        rugRisk: 0.001,
        populationBoost: 100,
        happinessEffect: 50,
        zoneRadius: 10,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_spire': {
    id: 'plasma_spire',
    name: 'Plasma Spire',
    category: 'plasma',
    footprint: { width: 1, height: 2 },
    icon: '🗼',
    isProcedural: true,
    cost: 8000,
    crypto: {
      tier: 'degen',
      chain: 'ethereum',
      description: 'A tall Plasma spire.',
      effects: {
        yieldRate: 9,
        volatility: 0.07,
        rugRisk: 0.001,
        populationBoost: 22,
        happinessEffect: 12,
        zoneRadius: 4,
        chainSynergy: ['ethereum'],
        categorySynergy: ['plasma'],
      },
    },
  },
  'plasma_nexus': {
    id: 'plasma_nexus',
    name: 'Plasma Nexus',
    category: 'plasma',
    footprint: { width: 3, height: 3 },
    icon: '🔮',
    isProcedural: true,
    cost: 22000,
    crypto: {
      tier: 'institution',
      chain: 'ethereum',
      description: 'The Plasma connection nexus.',
      effects: {
        yieldRate: 20,
        stakingBonus: 1.2,
        tradingFees: 15,
        volatility: 0.1,
        rugRisk: 0.002,
        populationBoost: 70,
        happinessEffect: 25,
        zoneRadius: 8,
        chainSynergy: ['ethereum', 'arbitrum', 'optimism', 'base'],
        categorySynergy: ['plasma', 'defi', 'chain'],
      },
    },
  },
};

// =============================================================================
// STABLECOIN BUILDINGS (3)
// =============================================================================
// Major stablecoin issuers and protocols.

export const STABLECOIN_BUILDINGS: Record<string, CryptoBuildingDefinition> = {
  'tether_hq': {
    id: 'tether_hq',
    name: 'Tether HQ',
    category: 'stablecoin',
    footprint: { width: 4, height: 3 },
    icon: '💵',
    isProcedural: true,
    cost: 30000,
    crypto: {
      tier: 'institution',
      protocol: 'Tether',
      chain: 'ethereum',
      launchYear: 2014,
      tvlTier: 'massive',
      description: 'The Tether HQ anchors stability with $120B+ in reserves.',
      effects: {
        yieldRate: 4,
        stakingBonus: 1.0,
        volatility: 0.01,
        rugRisk: 0.01,
        populationBoost: 100,
        happinessEffect: 15,
        zoneRadius: 12,
        chainSynergy: ['ethereum', 'solana', 'polygon', 'arbitrum'],
        categorySynergy: ['stablecoin', 'exchange', 'defi'],
      },
    },
  },
  'circle_tower': {
    id: 'circle_tower',
    name: 'Circle Tower',
    category: 'stablecoin',
    footprint: { width: 3, height: 3 },
    icon: '🔵',
    isProcedural: true,
    cost: 25000,
    crypto: {
      tier: 'institution',
      protocol: 'Circle',
      chain: 'ethereum',
      launchYear: 2018,
      tvlTier: 'massive',
      description: 'Circle Tower issues USDC with full regulatory compliance.',
      effects: {
        yieldRate: 3,
        stakingBonus: 1.02,
        volatility: 0.005,
        rugRisk: 0.005,
        populationBoost: 80,
        happinessEffect: 20,
        zoneRadius: 10,
        chainSynergy: ['ethereum', 'solana', 'base', 'arbitrum', 'polygon'],
        categorySynergy: ['stablecoin', 'exchange', 'defi'],
      },
    },
  },
  'ethena_labs': {
    id: 'ethena_labs',
    name: 'Ethena Labs',
    category: 'stablecoin',
    footprint: { width: 2, height: 2 },
    icon: '⚗️',
    isProcedural: true,
    cost: 12000,
    crypto: {
      tier: 'whale',
      protocol: 'Ethena',
      chain: 'ethereum',
      launchYear: 2024,
      tvlTier: 'high',
      description: 'Ethena Labs creates USDe, a high-yield synthetic dollar.',
      effects: {
        yieldRate: 25,
        stakingBonus: 1.25,
        volatility: 0.08,
        rugRisk: 0.03,
        airdropChance: 0.02,
        populationBoost: 40,
        happinessEffect: 8,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'arbitrum'],
        categorySynergy: ['stablecoin', 'defi'],
      },
    },
  },
};

// =============================================================================
// INFRASTRUCTURE BUILDINGS (5)
// =============================================================================
// Oracles, bridges, and core infrastructure protocols.

export const INFRASTRUCTURE_BUILDINGS: Record<string, CryptoBuildingDefinition> = {
  'chainlink_hub': {
    id: 'chainlink_hub',
    name: 'Chainlink Hub',
    category: 'infrastructure',
    footprint: { width: 3, height: 3 },
    icon: '🔗',
    isProcedural: true,
    cost: 22000,
    crypto: {
      tier: 'institution',
      protocol: 'Chainlink',
      chain: 'ethereum',
      launchYear: 2017,
      tvlTier: 'massive',
      description: 'Chainlink Hub provides price feeds powering all DeFi.',
      effects: {
        yieldRate: 8,
        stakingBonus: 1.15,
        volatility: 0.08,
        rugRisk: 0.002,
        populationBoost: 70,
        happinessEffect: 12,
        zoneRadius: 10,
        chainSynergy: ['ethereum', 'arbitrum', 'optimism', 'polygon', 'avalanche', 'base'],
        categorySynergy: ['infrastructure', 'defi'],
      },
    },
  },
  'the_graph_indexer': {
    id: 'the_graph_indexer',
    name: 'The Graph Indexer',
    category: 'infrastructure',
    footprint: { width: 2, height: 2 },
    icon: '📊',
    isProcedural: true,
    cost: 10000,
    crypto: {
      tier: 'whale',
      protocol: 'The Graph',
      chain: 'ethereum',
      launchYear: 2020,
      tvlTier: 'medium',
      description: 'The Graph Indexer organizes blockchain data for apps.',
      effects: {
        yieldRate: 6,
        stakingBonus: 1.08,
        volatility: 0.12,
        rugRisk: 0.005,
        populationBoost: 35,
        happinessEffect: 8,
        zoneRadius: 6,
        chainSynergy: ['ethereum', 'arbitrum', 'polygon'],
        categorySynergy: ['infrastructure'],
      },
    },
  },
  'pyth_observatory': {
    id: 'pyth_observatory',
    name: 'Pyth Observatory',
    category: 'infrastructure',
    footprint: { width: 2, height: 2 },
    icon: '🔮',
    isProcedural: true,
    cost: 11000,
    crypto: {
      tier: 'whale',
      protocol: 'Pyth',
      chain: 'solana',
      launchYear: 2021,
      tvlTier: 'medium',
      description: 'Pyth Observatory delivers high-frequency price data.',
      effects: {
        yieldRate: 10,
        stakingBonus: 1.1,
        volatility: 0.1,
        rugRisk: 0.008,
        airdropChance: 0.02,
        populationBoost: 30,
        happinessEffect: 6,
        zoneRadius: 5,
        chainSynergy: ['solana', 'ethereum', 'arbitrum', 'base'],
        categorySynergy: ['infrastructure', 'defi'],
      },
    },
  },
  'layerzero_bridge': {
    id: 'layerzero_bridge',
    name: 'LayerZero Bridge',
    category: 'infrastructure',
    footprint: { width: 2, height: 3 },
    icon: '🌉',
    isProcedural: true,
    cost: 14000,
    crypto: {
      tier: 'whale',
      protocol: 'LayerZero',
      chain: 'ethereum',
      launchYear: 2022,
      tvlTier: 'high',
      description: 'LayerZero Bridge enables omnichain messaging.',
      effects: {
        yieldRate: 12,
        tradingFees: 15,
        volatility: 0.15,
        rugRisk: 0.01,
        airdropChance: 0.03,
        populationBoost: 45,
        happinessEffect: 10,
        zoneRadius: 7,
        chainSynergy: ['ethereum', 'arbitrum', 'optimism', 'base', 'polygon', 'avalanche', 'bnb'],
        categorySynergy: ['infrastructure', 'chain'],
      },
    },
  },
  'wormhole_portal': {
    id: 'wormhole_portal',
    name: 'Wormhole Portal',
    category: 'infrastructure',
    footprint: { width: 2, height: 2 },
    icon: '🕳️',
    isProcedural: true,
    cost: 13000,
    crypto: {
      tier: 'whale',
      protocol: 'Wormhole',
      chain: 'solana',
      launchYear: 2021,
      tvlTier: 'high',
      description: 'Wormhole Portal connects Solana to 20+ blockchains.',
      effects: {
        yieldRate: 11,
        tradingFees: 12,
        volatility: 0.18,
        rugRisk: 0.015,
        populationBoost: 40,
        happinessEffect: 8,
        zoneRadius: 6,
        chainSynergy: ['solana', 'ethereum', 'sui', 'aptos', 'avalanche'],
        categorySynergy: ['infrastructure', 'chain'],
      },
    },
  },
};

// =============================================================================
// ALL CRYPTO BUILDINGS
// =============================================================================
// Combined registry of all crypto buildings.

export const ALL_CRYPTO_BUILDINGS: Record<string, CryptoBuildingDefinition> = {
  ...DEFI_BUILDINGS,
  ...EXCHANGE_BUILDINGS,
  ...CHAIN_BUILDINGS,
  ...CT_BUILDINGS,
  ...MEME_BUILDINGS,
  ...PLASMA_BUILDINGS,
  ...STABLECOIN_BUILDINGS,
  ...INFRASTRUCTURE_BUILDINGS,
};

// Get crypto building by ID
export function getCryptoBuilding(id: string): CryptoBuildingDefinition | undefined {
  return ALL_CRYPTO_BUILDINGS[id];
}

// Get all crypto buildings by category
export function getCryptoBuildingsByCategory(category: CryptoCategory): CryptoBuildingDefinition[] {
  return Object.values(ALL_CRYPTO_BUILDINGS).filter(b => b.category === category);
}

// Get all crypto building type IDs (keys of the building registry)
// The actual CryptoBuildingType is derived from these keys in buildingRegistry.ts
export function getCryptoBuildingTypes(): string[] {
  return Object.keys(ALL_CRYPTO_BUILDINGS);
}

// Total count: 22 DeFi + 7 Exchange + 13 Chain + 10 CT + 14 Meme + 18 Plasma + 3 Stablecoin + 5 Infrastructure = 92 buildings
export const CRYPTO_BUILDING_COUNT = Object.keys(ALL_CRYPTO_BUILDINGS).length;

